apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1004"
spec:
  description: Kubernetes metrics-server

  sourceRepos:
    - https://kubernetes-sigs.github.io/metrics-server/

  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
