apiVersion: v1
kind: Secret
metadata:
  name: cks-shared-ssh-authorized-keys
type: Opaque
stringData:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIAr6ZLvAnV5n8WHY8kWs2snLuMDZ1aJ2JiDSZv6y6mB student@local
