apiVersion: v1
kind: Namespace
metadata:
  name: task-01
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-admin
  namespace: task-01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: excessive-access
  namespace: task-01
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-admin-excessive-access
  namespace: task-01
subjects:
  - kind: ServiceAccount
    name: web-admin
    namespace: task-01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: excessive-access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-web
  namespace: task-01
  labels:
    app.kubernetes.io/name: insecure-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: insecure-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insecure-web
    spec:
      serviceAccountName: web-admin
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - name: http
              containerPort: 80
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: insecure-web
  namespace: task-01
spec:
  selector:
    app.kubernetes.io/name: insecure-web
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: task-01
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
