apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-svc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2004"
spec:
  project: argocd-svc
  source:
    repoURL: "https://github.com/dubovsky-andrey/k8s-cluster-public.git"
    path: argocd/argocd/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true