apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gateway-api
  namespace: argocd
spec:
  description: Gateway API CRDs

  sourceRepos:
    - https://github.com/dubovsky-andrey/k8s-cluster-public.git

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition