apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2050"
spec:
  project: moodle
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster-public.git
    path: argocd/moodle/manifests
    targetRevision: main
    directory:
      exclude: httproute.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: moodle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
