apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd-root-service"
  namespace: "argocd"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: "https://github.com/dubovsky-andrey/k8s-cluster-public.git"
    path: "argocd/"
    targetRevision: "main"
    directory:
      recurse: true
      include: "{**/application/*.yaml,**/project/*.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
