apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cks-exam-labs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1110"
spec:
  description: GitOps-driven CKS exam simulator labs

  sourceRepos:
    - https://github.com/dubovsky-andrey/k8s-cluster-public.git
    - https://charts.loft.sh

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: cks-lab-*
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: '*'
      kind: '*'
