rules_file:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml

json_output: false
log_level: info

stdout_output:
  enabled: true

file_output:
  enabled: false
  keep_alive: false
  filename: /tmp/falco.log
