apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cks-lab-16
resources:
  - namespace.yaml
  - ssh-authorized-key-secret.yaml
  - ssh-shell-base.yaml
  - common-rbac.yaml
  - ssh-pod.yaml
  - ssh-service.yaml
configMapGenerator:
  - name: cks-lab-16-task
    files:
      - task.txt=task-description.md
      - task-manifests.yaml=task-manifests.yaml
      - falco.yaml=falco.yaml
      - falco_rules.yaml=falco_rules.yaml
      - falco_rules.local.yaml=falco_rules.local.yaml
      - systemctl-sim.sh=systemctl-sim.sh
      - kubectl-sim.sh=kubectl-sim.sh
      - val.sh=val.sh
generatorOptions:
  disableNameSuffixHash: true
