apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2030"
spec:
  project: monitoring
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster-public.git
    path: argocd/monitoring-stuck/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
