apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2030"
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "85.1.3"
    helm:
      values: |
        crds:
          enabled: true
        grafana:
          admin:
            existingSecret: grafana-admin-credentials
            userKey: admin-user
            passwordKey: admin-password
          service:
            type: ClusterIP
          # kube-prometheus-stack-grafana
          resources:
            requests:
              cpu: 50m
              memory: 510Mi
            limits:
              cpu: 300m
              memory: 768Mi
        prometheus:
          service:
            type: ClusterIP
          # prometheus-kube-prometheus-stack-prometheus
          prometheusSpec:
            resources:
              requests:
                cpu: 200m
                memory: 312Mi
              limits:
                cpu: 200m
                memory: 612Mi
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            ruleSelector: {}
            ruleNamespaceSelector: {}
        alertmanager:
          # alertmanager-kube-prometheus-stack-alertmanager
          alertmanagerSpec:
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 50m
                memory: 64Mi
        # kube-prometheus-stack-operator
        prometheusOperator:
          resources:
            requests:
              cpu: 40m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        # kube-prometheus-stack-kube-state-metrics
        kube-state-metrics:
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 54Mi
        # kube-prometheus-stack-prometheus-node-exporter
        prometheus-node-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 50Mi
        nodeSelector:
          kubernetes.io/arch: amd64
        tolerations:
          - operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
