apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-svc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  description: Argocd-Service

  sourceRepos:
    - https://github.com/dubovsky-andrey/k8s-cluster-public.git

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'