apiVersion: v1
kind: ConfigMap
metadata:
  name: cks-shell-base
data:
  bashrc: |
    export CKS_LAB_NAME=cks-lab-02
    export KUBECONFIG=/home/student/.kube/config
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    fi
    if command -v kubectl >/dev/null 2>&1 && type _get_comp_words_by_ref >/dev/null 2>&1; then
      source <(kubectl completion bash)
      complete -o default -F __start_kubectl k
    fi
    alias k=kubectl
    alias kgp='kubectl get pods'
    alias kga='kubectl get all'
    PS1='student@${CKS_LAB_NAME:-cks-lab}:\w$ '
