apiVersion: v1
kind: Namespace
metadata:
  name: omni
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-default
  namespace: omni
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: omni
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe
  namespace: omni
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend
  namespace: omni
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fe
  namespace: omni
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend
  namespace: omni
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: omni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fe
  namespace: omni
subjects:
  - kind: ServiceAccount
    name: fe
    namespace: omni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fe
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: frontend-site
  namespace: omni
spec:
  serviceAccountName: fe
  containers:
    - image: nginx:alpine
      name: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-volume
      resources: {}
  volumes:
    - name: test-volume
      hostPath:
        path: /data/pages
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-site
  namespace: omni
spec:
  selector:
    run: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
