apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: adguardhome
---
apiVersion: v1
kind: Namespace
metadata:
  name: moodle
---
apiVersion: v1
kind: Namespace
metadata:
  name: calibre
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatewayapi
