apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2003"
spec:
  project: gatewayapi
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster-public.git
    path: argocd/cilium-gwa/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: gatewayapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
