apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2060"
spec:
  project: homarr
  source:
    repoURL: https://homarr-labs.github.io/charts/
    chart: homarr
    targetRevision: "8.19.0"
    helm:
      valuesObject:
        image:
          repository: ghcr.io/homarr-labs/homarr
          tag: v1.61.0
        service:
          enabled: true
          type: ClusterIP
          port: 7575
        persistence:
          homarrDatabase:
            enabled: true
            volumeClaimName: homarr-database
            size: 5Gi
        database:
          externalDatabaseEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
