apiVersion: v1
kind: Service
metadata:
  name: cks-shell-ssh
  labels:
    app.kubernetes.io/name: cks-shell
    app.kubernetes.io/part-of: cks-lab-05
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cks-shell
    app.kubernetes.io/part-of: cks-lab-05
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
      nodePort: 32005
