apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cks-lab-10-vcluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2218"
spec:
  project: cks-exam-labs
  sources:
    - repoURL: https://charts.loft.sh
      chart: vcluster
      targetRevision: 0.34.0
      helm:
        releaseName: lab-10
        valueFiles:
          - $values/cks-exam-labs/manifests/labs/lab-10/vcluster-values.yaml
    - repoURL: https://github.com/dubovsky-andrey/k8s-cluster-public.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cks-lab-10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
