apiVersion: v1
kind: Pod
metadata:
  name: connector
  namespace: production
spec:
  containers:
    - name: connector
      image: registry.example.com/connector:1.4
      env:
        - name: CONNECTOR_PASSWORD
          value: P@sSw0rd
      resources: {}
