apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle-project
    app.kubernetes.io/instance: n7
spec:
  selector:
    app.kubernetes.io/name: moodle
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30011
