apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-l2-loadbalancer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2000"
spec:
  project: cilium-lb
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster-public.git
    path: argocd/cilium-lb/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
