apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: calibre
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
  volumeName: calibre-pv-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-books
  namespace: calibre
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
  volumeName: calibre-pv-books
