apiVersion: v1
kind: Namespace
metadata:
  name: prod
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: moodle 
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: system
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: calibre
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatewayapi
spec: {}
status: {}