apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: System-level addons managed via ArgoCD

  sourceRepos:
    - https://github.com/dubovsky-andrey/k8s-cluster-public.git
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts

  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
