apiVersion: v1
kind: Service
metadata:
  name: argocd-server-svc
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30080
