apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: moodle
  source:
    repoURL: "git@github.com:dubovsky-andrey/k8s-cluster-public.git"
    path: argocd/charts/moodle
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true