apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguardhome
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: adguardhome
  source:
    repoURL: "https://github.com/dubovsky-andrey/k8s-cluster-public.git"
    path: argocd/charts/adguardhome
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true