apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: books
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
      - name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        ports:
        - name: http
          containerPort: 8083
        volumeMounts:
        - name: config
          mountPath: /config
        - name: books
          mountPath: /books
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
#       volumes:
#       - name: config
#         persistentVolumeClaim:
#           claimName: calibre-web-config
#       - name: books
#         persistentVolumeClaim:
#           claimName: calibre-web-books
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: calibre-web
#   namespace: books
# spec:
#   type: NodePort
#   selector:
#     app: calibre-web
#   ports:
#   - name: http
#     port: 8083
#     targetPort: 8083
#     nodePort: 30010
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: calibre-web-config
#   namespace: books
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: calibre-web-books
#   namespace: books
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
