apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: "0.15.2"
      helm:
        values: |
          controller:
            tolerations:
              - effect: NoSchedule
                operator: Exists
          speaker:
            tolerations:
              - effect: NoSchedule
                operator: Exists

    - repoURL: git@github.com:dubovsky-andrey/k8s-cluster-private.git
      targetRevision: main
      path: argocd/charts/metallb/

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
