controlPlane:
  proxy:
    extraSANs:
      - lab-07
      - lab-07.cks-lab-07
      - lab-07.cks-lab-07.svc
      - lab-07.cks-lab-07.svc.cluster.local
  distro:
    k8s:
      enabled: true
      image:
        tag: v1.34.0
  statefulSet:
    persistence:
      volumeClaim:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi

exportKubeConfig:
  server: https://lab-07.cks-lab-07.svc.cluster.local:443

sync:
  toHost:
    pods:
      enabled: true
    services:
      enabled: true
    secrets:
      enabled: true
    configMaps:
      enabled: true
    persistentVolumeClaims:
      enabled: true
