apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gatewayapi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1003"
spec:
  description: Cilium Gateway API routes

  sourceRepos:
    - https://github.com/dubovsky-andrey/k8s-cluster-public.git
    - https://github.com/kubernetes-sigs/gateway-api.git

  destinations:
    - namespace: gatewayapi
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: moodle
      server: https://kubernetes.default.svc
    - namespace: calibre
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
