apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cks-lab-03
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2221"
spec:
  project: cks-exam-labs
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster-public.git
    path: cks-exam-labs/manifests/labs/lab-03
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cks-lab-03
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
