apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: calibre
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1040"
spec:
  description: calibre

  sourceRepos:
    - https://github.com/dubovsky-andrey/k8s-cluster-public.git

  destinations:
    - namespace: calibre
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume

  namespaceResourceWhitelist:
    - group: apps
      kind: StatefulSet
    - group: ''
      kind: Service
    - group: ''
      kind: PersistentVolumeClaim
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: cilium.io
      kind: CiliumNetworkPolicy
