apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: csi-driver-smb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1002"
spec:
  description: SMB CSI driver

  sourceRepos:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts

  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
